version: '3.4'

services:
  motus:
    image: motus
  auth:
    image: auth
    build:
      context: auth
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  
