version: '3.4'

networks:
  monitor-net:
    name: monitor-net
services:
  motus:
    image: motus
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 8080:8080
    build:
      context: motus
      dockerfile: Dockerfile
  auth:
    image: auth
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 5000:5000
    build:
      context: auth
      dockerfile: Dockerfile
  score:
    image: score
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports: 
    - 4000:4000
    build:
      context: score
      dockerfile: Dockerfile
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - monitor-net
  loki:
    image: grafana/loki
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    restart: unless-stopped
    networks:
      - monitor-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - monitor-net