version: '3.4'

services:
  motus:
    image: motus
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  auth:
    image: auth
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  score:
    image: score
    environment:
      NODE_ENV: production
    ports: 
    - 4000:4000
