version: '3.4'

networks:
  monitor-net:
    name: monitor-net
services:
  motus:
    image: motus
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    build:
      context: motus
      dockerfile: Dockerfile
  auth:
    image: auth
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    build:
      context: auth
      dockerfile: Dockerfile
  score:
    image: score
    environment:
      NODE_ENV: production
    ports: 
    - 4000:4000
    build:
      context: score
      dockerfile: Dockerfile
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - monitor-net
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    restart: unless-stopped
    networks:
      - monitor-net